### ISSUE TITLE
Incorrect  formatting when using lists 

### ISSUE THREAD

**Issue by markusleh** [codeskills-dev/md-to-react-email#11]
Hi

The following markdown is showing up incorrectly:

```
# Title

## Subtitle

* List

## Subtitle2

Normal text

* List2
```

`Subtitle` and `Subtitle2` should be in the same indentation:

<img width="330" alt="image" src="https://github.com/codeskills-dev/md-to-react-email/assets/28872014/5e000c2a-0eb4-4640-92e0-684456e3a0c1">

Instead, this is rendered as:

<img width="460" alt="image" src="https://github.com/codeskills-dev/md-to-react-email/assets/28872014/248170c1-40bc-4411-8e95-ed24a7ebb786">

Looking at the rendered HTML, it seems that everything gets wrapped in a `<ul>` and it is not closed until the end of the markdown.
<img width="1222" alt="image" src="https://github.com/codeskills-dev/md-to-react-email/assets/28872014/8f01c965-67d9-4580-9a3f-d499baaa4a19">
 
I am using version 3.0.4

**Comment by lordelogos** [comment]
Hello @markusleh,

This issue has been resolved in the [new release](https://www.npmjs.com/package/md-to-react-email/v/4.0.0)
Thank you for your patience.
