### ISSUE TITLE
`import` syntax is incorrect

### ISSUE THREAD

**Issue by DevDario** [codeskills-dev/md-to-react-email#15]
![error](https://github.com/codeskills-dev/md-to-react-email/assets/101002847/50a85676-a154-4086-a3c1-e9787112d2d1)

**Comment by lordelogos** [comment]
Hi @DevDario,

Thank you for pointing this out. 

Are you interested in making a PR for this?
The repo for the docs is here: https://github.com/codeskills-dev/md-to-react-email-docs

**Comment by DevDario** [comment]
Sure, @lordelogos

**Comment by DevDario** [comment]
@lordelogos I've made the PR, you can now review it 😉

**Comment by lordelogos** [comment]
@DevDario, PR has been merged. 
Thank you!

**Comment by DevDario** [comment]
It was my pleasure
