### ISSUE TITLE
The first Example Component does not work 

### ISSUE THREAD

**Issue by andreyscott** [codeskills-dev/md-to-react-email#2]
`
import {ReactEmailMarkdown} from "md-to-react-email"

  export default function EmailTemplate() {
  return (
          <Email>
                  <Head />
                  <Section>
                  <ReactEmailMarkdown markdown={`# Hello, World!`} />
                  </Section>
          </Email>
  )
  }
`
The first component in the example doesn't work and shows an error for some reason 
Email, Head, and Section are components but are not Defined initially
and when trying to import it manually like so below
`import {Head, Email, Section} from "md-to-react-email"
` 
another error shows up in console
_export 'Email' (imported as 'Email') was not found in 'md-to-react-email' (possible exports: ReactEmailMarkdown, camelToKebabCase, parseCssInJsToInlineCss, parseMarkdownToReactEmail, parseMarkdownToReactEmailJSX, patterns, styles)_

**Comment by lordelogos** [comment]
This package is used alongside [react-email](https://react.email). The other components are from `react-email`.

You can not use this package without using `react-email`
