### ISSUE TITLE
react-email as peer dependency

### ISSUE THREAD

**Issue by seagullua** [codeskills-dev/md-to-react-email#20]
We are trying to build a standalone microservice to render emails. md-to-react-email has a peer-dependency of react-email which has nextjs so we have node_modules of 500MB

**Comment by brandon-pereira** [comment]
Also seeing this problem in our app too..

**Comment by lordelogos** [comment]
Hey @seagullua, 

The peer-dependency of react-email was removed in v5. You should not have that issue if you upgrade to v5
