### ISSUE TITLE
Issue with Paragraphs

### ISSUE THREAD

**Issue by GiovanniKaaijk** [codeskills-dev/md-to-react-email#3]
I've been using react-email in a project which depends on md-to-react-email and I have encountered an issue where paragraphs are not being parsed and rendered as expected.

In standard Markdown, text separated by a blank line should be interpreted as separate paragraphs and should be wrapped in <p> tags when converted to HTML. However, when using md-to-react-email, it seems that this is not the case. Here's an example:

**Markdown Input:**
```
This is a paragraph

This is another paragraph
```

**Expected output:**
```
<p>This is a paragraph</p>
<p>This is another paragraph</p>
```

**Actual Output:**
`<div>This is a paragraph This is another paragraph</div>`

Additionally, when using bold syntax `**text**`, the text is being wrapped in a `<p>` tag with a bold style, rather than being converted to a `<strong>` tag, which is the standard behavior for a Markdown processor.

**Markdown input:**
`This is a **bold** text`

**Expected output:**
`<p>This is a <strong>bold</strong> text</p>`

**Actual output:**
`<p>This is a <p style="font-weight:bold">bold</p> text</p>`

Can you please look into these issues? Paragraphs and bold text are pretty fundamental features of Markdown, and it would be great to have them working properly in md-to-react-email.

**Comment by mitchmeister** [comment]
just started using & also having these problems.

**Comment by lordelogos** [comment]
Hi @GiovanniKaaijk and @mitchmeister, 

Thank you for your feedback. I have already implemented a fix for the bold issue and I am currently working on the paragraph issue. However, I am open to any suggestions on how the `<p>` issue should be resolved.

The main issues have always been the one of `<p>` tags wrapping around other markdown elements and also the placement of opening and closing <p> tags which was why they were initially removed.

Example of this can be seen below
```
This **is** a paragraph.
## This is a header.
- This is a list item.
- This is another list item.
This is a [link](https://www.google.com/).
```

This can be converted in the following ways:
- 1

```
<p> This <strong>is</strong> a paragraph</p>

<h2>This is a header.</h2>
<ul>
    <li>This is a list item</li>
    <li>This is another list item</li>
</ul>

<p>This is a <a href="https://www.google.com">link</a></p>
```

- 2
```
<p> This <strong>is</strong> a paragraph</p>
<p>
    <h2>This is a header.</h2>
    <ul>
        <li>This is a list item</li>
        <li>This is another list item</li>
    </ul>
</p>

<p>This is a <a href="https://www.google.com">link</a></p>

```

- 3
```
<p> 
    This <strong>is</strong> a paragraph
    <h2>This is a header.</h2>
    <ul>
        <li>This is a list item</li>
        <li>This is another list item</li>
    </ul>
</p>

<p>This is a <a href="https://www.google.com">link</a></p>

```

In the examples, the `<p>` tag wraps around the elements at different positions which can be determined by the number of line-breaks at the end of each line. There are also many other factors to consider as people do not generally write markdown in one uniform way.

All of this is to say, I am open to suggestions on how to handle the `<p>` issue as it is something that has been on my mind since v1 of `md-to-react-email` but I have not yet come to a suitable solution that works for majority of users.

**Comment by mitchmeister** [comment]
#2 & #3 are clearly wrong as the <p> tag shouldn't wrap any other tags other than <b> (or <strong>), <i> & <a>. 

isn't #1 the obvious answer?

**Comment by lordelogos** [comment]
> #2 & #3 are clearly wrong as the `<p>` tag shouldn't wrap any other tags other than `<b>` (or `\<strong\>`), `<i>` & `<a>`.
> 
> isn't #1 the obvious answer?

What are you thoughts on images. should they be inline in `<p>` tags or they should always be block level too?

**Comment by GiovanniKaaijk** [comment]
@lordelogos, 

Thank you for your effort in addressing this issue and your openness to suggestions.

Regarding your question on how to handle images, I believe it would be most appropriate to treat images as block-level elements. This means that an image should be outside of the `<p>` tags. My reasoning is as follows:

1. Images often represent standalone content that is not necessarily a direct part of the text flow, unlike `<b>`, `<strong>`, `<i>`, and `<a>` tags which are typically part of the text itself.
2. Rendering an image within a `<p>` tag can sometimes cause display issues in various email clients, leading to inconsistent results. 

Therefore, for the best possible compatibility and predictability, I suggest we keep `<img>` tags outside of `<p>` tags, treating them as block-level elements.

Thanks again for your work on this.

**Comment by mitchmeister** [comment]
> What are you thoughts on images. should they be inline in `<p>` tags or they should always be block level too?

block level.

**Comment by hasparus** [comment]
@GiovanniKaaijk Just FYI, if it's blocking you — I've worked around this issue by turning `parseMarkdownToReactEmailJSX` from `md-to-react-email` into a vistor using `remark-parse` and `rehype-react`. Posted the workaround here: https://github.com/codeskills-dev/md-to-react-email/issues/4#issuecomment-1634087677.

**Comment by lordelogos** [comment]
Hello Everyone, 

Thank you for your feedback on this. I am currently wrapping things up for the next release which should fix these issues. 
I will try to push this out before the weekend. 

Thank you once again for your feedback and suggestions. 🙏

**Comment by lordelogos** [comment]
Hi, 

Just an update, [v3.0.4](https://www.npmjs.com/package/md-to-react-email) has just been released and it solves all the issues that were brought up. 
Thank you for your patience and feedback.

**Comment by mitchmeister** [comment]
thanks Paul 🙏🏻

**Comment by GiovanniKaaijk** [comment]
Many thanks!
