### ISSUE TITLE
can you please extend documentation to show how to pass custom styles to <ReactEmailMarkdown>

### ISSUE THREAD

**Issue by mitchmeister** [codeskills-dev/md-to-react-email#9]
I'm trying to edit the css of various html tags (eg. `<p>` & `<img>`) & I'm not clear how to do this.  Also what is the distinction between markdownCustomStyles & markdownContainerStyles.  Or (& my apologies in advance if this is the case) point me in the direction of existing documentation.

thanks, Mitch

**Comment by lordelogos** [comment]
Hey @mitchmeister,

I am currently working on extending the documentation to cover everything in a bit more depth. 

For your question on `markdownCustomStyles` vs `markdownContainerStyles`

The custom styles are where you pass styles for the various html tags (p, link, h1)

The container styles are styles for the wrapping div
![Screenshot 2023-07-17 at 15 15 01](https://github.com/codeskills-dev/md-to-react-email/assets/67395687/071bf59e-1afc-4072-bba2-1d94cd752011)

I will update you when the docs are up.

**Comment by lordelogos** [comment]
Hi @mitchmeister, 

The docs are now live. You can find them [here](https://md2re.codeskills.dev/)
Thank you for your patience.
